export const GET_MODULES_LIST_REQUEST = "GET_MODULES_LIST_REQUEST" 
export const GET_MODULES_LIST_SUCCESS = "GET_MODULES_LIST_SUCCESS" 
export const GET_MODULES_LIST_FAILED = "GET_MODULES_LIST_FAILED"