export const GET_MODULES_DETAILS_REQUEST = "GET_MODULES_DETAILS_REQUEST" 
export const GET_MODULES_DETAILS_SUCCESS = "GET_MODULES_DETAILS_SUCCESS" 
export const GET_MODULES_DETAILS_FAILED = "GET_MODULES_DETAILS_FAILED"